
BEGIN;
DECLARE curs SCROLL CURSOR FOR SELECT * FROM products;
FETCH LAST FROM cus;
MOVE ABSOLUTE 15 FROM curs;
FETCH FROM curs;
MOVE RELATIVE -8 FROM curs;
FETCH FROM curs;
MOVE ABSOLUTE 2 FROM curs;
FETCH FROM curs;
FETCH PRIOR FROM curs;
CLOSE curs;
COMMIT;